import {nzCalendarDay} from '../../../../lib/time';
import {NextResponse} from 'next/server';
import {adminClient} from '../../../../lib/supabase';
import {computeListingSignals,computeProductMetrics} from '../../../../lib/intelligence';
function extractText(j:any){if(typeof j.output_text==='string')return j.output_text;for(const o of j.output||[])for(const c of o.content||[])if(c.type==='output_text'&&c.text)return c.text;return ''}
const nzDay=()=>nzCalendarDay();
function drastic(oldS:any,newS:any){if(!oldS||oldS.summary_version!==newS.summary_version)return true;return oldS.product_count!==newS.product_count||oldS.strong_count!==newS.strong_count||Math.abs((oldS.open_issues||0)-(newS.open_issues||0))>=2||Math.abs((oldS.good||0)-(newS.good||0))>=2||Math.abs((oldS.watching||0)-(newS.watching||0))>=3||Math.abs((oldS.failed_listings||0)-(newS.failed_listings||0))>=2}
export async function POST(req:Request){
 try{
  if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:'OPENAI_API_KEY is not configured'},{status:503});
  const {force=false}=await req.json().catch(()=>({force:false}));const db=adminClient();
  const [{data:products},{data:listings},{data:obs},{data:links},{data:errs},{data:events}]=await Promise.all([
   db.from('products').select('*').is('archived_at',null).limit(100),db.from('listings').select('*').limit(250),
   db.from('observations').select('listing_uuid,captured_at,views,watchers,bids,buy_now_nzd,asking_price_nzd,current_bid_nzd,close_date,close_remaining').order('captured_at',{ascending:false}).limit(5000),
   db.from('product_listings').select('*'),db.from('collection_errors').select('status').eq('status','open'),db.from('system_events').select('status,severity').eq('status','open')
  ]);
  const baseLs=(listings||[]).map((l:any)=>({...l,observations:(obs||[]).filter((o:any)=>o.listing_uuid===l.id).slice(0,40)}));
  const signals=computeListingSignals(baseLs);const ls=baseLs.map((l:any,i:number)=>({...l,signal:signals[i]}));const researchLs=ls.filter((l:any)=>l.metadata?.ownership!=='own');
  const ps=(products||[]).map((p:any)=>{const productLinks=(links||[]).filter((x:any)=>x.product_id===p.id&&x.role!=='own');const ids=new Set(productLinks.map((x:any)=>x.listing_uuid));const pls=researchLs.filter((l:any)=>l.product_id===p.id||ids.has(l.id)).map((l:any)=>({...l,comparableMatch:productLinks.find((x:any)=>x.listing_uuid===l.id)||null}));return {id:p.id,name:[p.vehicle_make,p.vehicle_model,p.chassis,p.part_type].filter(Boolean).join(' ')||p.part_type||'Untitled product',status:p.status,metrics:computeProductMetrics(p,pls)}});
  const snapshot={summary_version:6,product_count:ps.length,strong_count:ps.filter((p:any)=>['STRONG','SCALE'].includes(p.metrics.verdict)).length,open_issues:(errs||[]).length+(events||[]).filter((x:any)=>['warning','error','critical'].includes(x.severity)).length,good:researchLs.filter((x:any)=>x.signal.label==='GOOD').length,watching:researchLs.filter((x:any)=>x.signal.label==='WATCHING').length,must_have:researchLs.filter((x:any)=>x.signal.label==='MUST_HAVE').length,failed_listings:researchLs.filter((x:any)=>(x.consecutive_failures||0)>0).length,new_24h:researchLs.filter((x:any)=>x.first_seen&&Date.now()-Date.parse(x.first_seen)<86400000).length,listing_count:researchLs.length};
  const day=nzDay();const {data:cached}=await db.from('daily_briefs').select('*').eq('brief_date',day).maybeSingle();
  if(cached&&!force&&!drastic(cached.trigger_snapshot,snapshot))return NextResponse.json({ok:true,summary:cached.summary,analysis:cached.analysis,cached:true,generated_at:cached.generated_at});
  const topListings=[...researchLs].sort((a:any,b:any)=>b.signal.score-a.signal.score).slice(0,14).map((x:any)=>({research_id:`CB-${String(x.marketplace||'TM').toUpperCase().includes('TRADE')?'TM':String(x.marketplace||'MP').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3)}-${x.listing_id}`,listing_id:x.listing_id,title:x.title,seller:x.seller,marketplace:x.marketplace,part_type:x.part_type,signal:x.signal,failures:x.consecutive_failures||0}));
  const prompt=`You are COBALT, Motera's marketplace research analyst. Your overview must tell Liam what the market research is DISCOVERING today, not describe the software dashboard. Synthesize product/category patterns from the evidence. Lead with the strongest product family or category showing recent attention. Prefer corroborated patterns across multiple independent listings/sellers over a single hot listing. Use recent view velocity, 24h view change, acceleration, bids/watchers when exposed, close-date context, peer-relative performance, seller diversity and evidence depth. Mention a standout individual listing only when it adds useful context, and include its research_id when you do. End with at most one short caveat if limited observation depth materially affects confidence. Do NOT lead with or waste summary space on product counts, queue counts, issue counts, scraper failures, generic system health, or phrases such as 'commercial read'; those already appear elsewhere. Never claim a sale from views, bids, expiry or disappearance. Return ONLY JSON with keys summary, highlights (array max 4), next_action. Write for a founder who is new to marketplace and sales terminology. Summary should be 30-48 words, maximum 55, conversational, plain English, specific and useful. Prefer everyday wording such as 'getting more views', 'more people seem interested', 'several sellers show the same pattern', and 'we need more observations'. Avoid unexplained jargon such as velocity, acceleration, demand signal, conversion, margin, corroboration, confidence interval, sell-through, liquidity, or SKU. If a technical/sales term is genuinely useful, explain it immediately in simple words in the same sentence, for example: 'view velocity (how quickly views are increasing)'. The summary should tell Liam what appears interesting, why COBALT thinks so, and what that means for the next decision. Example style: 'Aqua window switches look the most interesting today. Several separate listings are gaining views, which suggests people are actively looking at this type of part rather than just one listing getting lucky. Combination switches are also worth watching, but we need a little more data before acting.'\n\nDASHBOARD:${JSON.stringify(snapshot)}\nPRODUCTS:${JSON.stringify(ps)}\nTOP_QUEUE_LISTINGS:${JSON.stringify(topListings)}`;
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:prompt})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'OpenAI request failed');const text=extractText(j).trim();let analysis:any;try{analysis=JSON.parse(text.replace(/^```json\s*|```$/g,''))}catch{analysis={summary:text,highlights:[],next_action:'Review the dashboard'}};const words=String(analysis.summary||'').trim().split(/\s+/);if(words.length>55)analysis.summary=words.slice(0,55).join(' ')+'…';const row={brief_date:day,summary:analysis.summary,analysis,trigger_snapshot:snapshot,model:process.env.OPENAI_MODEL||'gpt-5.6-luna',generated_at:new Date().toISOString()};const {error}=await db.from('daily_briefs').upsert(row,{onConflict:'brief_date'});if(error)throw error;return NextResponse.json({ok:true,summary:analysis.summary,analysis,cached:false,generated_at:row.generated_at});
 }catch(e:any){return NextResponse.json({error:e.message||'Daily summary failed'},{status:500})}
}
