create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  slug text unique,
  vehicle_make text,
  vehicle_model text,
  chassis text,
  part_type text not null,
  status text not null default 'discovery' check (status in ('discovery','tracking','validated','sourcing','sampling','selling','hold','rejected')),
  priority integer not null default 50 check (priority between 0 and 100),
  target_retail_nzd numeric(12,2),
  target_landed_cost_nzd numeric(12,2),
  opportunity_score numeric(6,2),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.products(id) on delete set null,
  marketplace text not null default 'Trade Me',
  listing_id text not null,
  url text not null,
  source_url text,
  title text,
  seller text,
  active boolean not null default true,
  first_seen timestamptz not null default now(),
  last_seen timestamptz,
  last_observed_at timestamptz,
  next_observation_at timestamptz,
  observation_interval_hours integer not null default 24 check (observation_interval_hours between 1 and 8760),
  priority integer not null default 50 check (priority between 0 and 100),
  consecutive_failures integer not null default 0,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(marketplace, listing_id)
);

create index if not exists listings_due_idx on public.listings(active, next_observation_at);
create index if not exists listings_product_idx on public.listings(product_id);

create table if not exists public.observations (
  id bigint generated by default as identity primary key,
  listing_uuid uuid not null references public.listings(id) on delete cascade,
  captured_at timestamptz not null,
  collector_version text,
  listing_mode text,
  buy_now_nzd numeric(12,2),
  asking_price_nzd numeric(12,2),
  starting_price_nzd numeric(12,2),
  current_bid_nzd numeric(12,2),
  views integer,
  watchers integer,
  bids integer,
  close_date timestamptz,
  close_remaining text,
  condition text,
  location text,
  seller text,
  seller_feedback_pct numeric(8,3),
  seller_feedback_count integer,
  seller_in_trade boolean,
  seller_address_verified boolean,
  seller_member_since text,
  shipping_options jsonb,
  pickup_available boolean,
  part_number text,
  part_number_candidates jsonb,
  vehicle text,
  chassis text,
  years text,
  engine_code text,
  part_type text,
  extraction_score integer,
  quality_flags jsonb,
  raw_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique(listing_uuid, captured_at)
);

create index if not exists observations_listing_time_idx on public.observations(listing_uuid, captured_at desc);

create table if not exists public.collection_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  source text not null,
  listings_attempted integer not null default 0,
  listings_succeeded integer not null default 0,
  listings_failed integer not null default 0,
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  company_name text not null unique,
  platform text default 'Alibaba',
  supplier_url text,
  contact_name text,
  contact_method text,
  score numeric(4,2),
  status text default 'screening',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supplier_quotes (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.products(id) on delete cascade,
  supplier_id uuid references public.suppliers(id) on delete cascade,
  quoted_at timestamptz default now(),
  sample_qty integer,
  sample_unit_price numeric(12,4),
  qty_10_price numeric(12,4),
  qty_50_price numeric(12,4),
  qty_100_price numeric(12,4),
  currency text,
  moq integer,
  shipping_to_nz numeric(12,2),
  warranty text,
  lead_time_days integer,
  fitment_confidence integer check (fitment_confidence between 0 and 100),
  response_notes text,
  raw_response text,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at before update on public.listings for each row execute function public.set_updated_at();
drop trigger if exists suppliers_set_updated_at on public.suppliers;
create trigger suppliers_set_updated_at before update on public.suppliers for each row execute function public.set_updated_at();
