-- COBALT V3.9.4 — scheduler forensics and durable automation health telemetry

create table if not exists public.scheduler_runs (
  id bigint generated by default as identity primary key,
  github_run_id text not null,
  github_run_attempt integer not null default 1,
  github_event_name text,
  github_sha text,
  github_ref text,
  workflow_name text,
  cobalt_version text,
  runner_os text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  stage text not null default 'started',
  status text not null default 'running' check (status in ('running','success','no_due','partial','failed')),
  active_listing_count integer,
  due_count integer,
  selected_count integer,
  oldest_due_at timestamptz,
  oldest_overdue_seconds integer,
  candidate_listing_ids jsonb not null default '[]'::jsonb,
  dependency_attempts integer,
  preflight_attempts integer,
  worker_run_id bigint references public.collection_runs(id) on delete set null,
  listings_attempted integer not null default 0,
  listings_succeeded integer not null default 0,
  listings_failed integer not null default 0,
  error_type text,
  error_message text,
  diagnostics jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(github_run_id, github_run_attempt)
);

create index if not exists scheduler_runs_started_idx on public.scheduler_runs(started_at desc);
create index if not exists scheduler_runs_status_idx on public.scheduler_runs(status, started_at desc);

create or replace function public.scheduler_runs_set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists scheduler_runs_set_updated_at on public.scheduler_runs;
create trigger scheduler_runs_set_updated_at before update on public.scheduler_runs
for each row execute function public.scheduler_runs_set_updated_at();

grant select, insert, update, delete on public.scheduler_runs to service_role;
grant usage, select on sequence public.scheduler_runs_id_seq to service_role;
