-- COBALT V3.9.5 — relist lifecycle + comparable matcher trace
create extension if not exists pgcrypto;

alter table public.listings add column if not exists listing_family_id uuid;
alter table public.listings add column if not exists relisted_from uuid references public.listings(id) on delete set null;
alter table public.listings add column if not exists lifecycle_state text not null default 'active';
alter table public.listings add column if not exists lifecycle_episode integer not null default 1;
alter table public.listings add column if not exists relist_check_count integer not null default 0;
alter table public.listings add column if not exists relist_watch_until timestamptz;
alter table public.listings add column if not exists last_relisted_at timestamptz;

update public.listings set listing_family_id=id where listing_family_id is null;
alter table public.listings alter column listing_family_id set default gen_random_uuid();
create index if not exists listings_family_idx on public.listings(listing_family_id);
create index if not exists listings_relist_watch_idx on public.listings(lifecycle_state,next_observation_at);

alter table public.observations add column if not exists lifecycle_episode integer not null default 1;

create table if not exists public.listing_lifecycle_events (
  id bigint generated by default as identity primary key,
  listing_uuid uuid not null references public.listings(id) on delete cascade,
  listing_family_id uuid,
  marketplace text not null,
  marketplace_listing_id text not null,
  episode integer not null,
  event_type text not null,
  occurred_at timestamptz not null default now(),
  previous_listing_uuid uuid references public.listings(id) on delete set null,
  confidence numeric(6,5),
  reason jsonb not null default '{}'::jsonb
);
create index if not exists lifecycle_events_listing_idx on public.listing_lifecycle_events(listing_uuid,occurred_at desc);
create index if not exists lifecycle_events_family_idx on public.listing_lifecycle_events(listing_family_id,occurred_at desc);

create table if not exists public.matcher_debug_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  source text not null,
  matcher_version text not null default 'hybrid-v1',
  product_id uuid references public.products(id) on delete cascade,
  product_name text,
  listing_uuid uuid references public.listings(id) on delete cascade,
  marketplace text,
  marketplace_listing_id text,
  listing_title text,
  decision text not null,
  score numeric(6,5),
  cosine numeric(6,5),
  reasons jsonb not null default '[]'::jsonb,
  shape jsonb not null default '{}'::jsonb
);
create index if not exists matcher_debug_time_idx on public.matcher_debug_events(occurred_at desc);
create index if not exists matcher_debug_listing_idx on public.matcher_debug_events(listing_uuid,occurred_at desc);

grant select,insert,update,delete on public.listing_lifecycle_events to service_role;
grant select,insert,update,delete on public.matcher_debug_events to service_role;
grant usage,select on sequence public.listing_lifecycle_events_id_seq to service_role;
grant usage,select on sequence public.matcher_debug_events_id_seq to service_role;
