-- COBALT V3.9.17: category-agnostic user interest suppression.
-- A negative preference is durable evidence, not deletion. Profiles are intentionally
-- generic so the same mechanism works for vehicle parts, kitchenware, toys, watches, etc.

create table if not exists public.interest_suppressions (
  id uuid primary key default gen_random_uuid(),
  source_listing_uuid uuid references public.listings(id) on delete cascade,
  scope text not null default 'similar' check (scope in ('listing','similar')),
  matcher_version text not null default 'generic-interest-v1',
  signature_text text not null,
  category_path jsonb not null default '[]'::jsonb,
  reference_snapshot jsonb not null default '{}'::jsonb,
  threshold numeric(5,4) not null default 0.7000,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_listing_uuid, scope)
);

create index if not exists interest_suppressions_active_idx on public.interest_suppressions(active, created_at desc);

create table if not exists public.interest_suppression_hits (
  id bigint generated by default as identity primary key,
  suppression_id uuid references public.interest_suppressions(id) on delete set null,
  marketplace text,
  marketplace_listing_id text,
  title text,
  url text,
  score numeric(6,4),
  evidence jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists interest_suppression_hits_time_idx on public.interest_suppression_hits(occurred_at desc);

create or replace function public.set_interest_suppression_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists interest_suppressions_set_updated_at on public.interest_suppressions;
create trigger interest_suppressions_set_updated_at before update on public.interest_suppressions for each row execute function public.set_interest_suppression_updated_at();
