-- COBALT V3.10.0 — marketplace Search Watches + acquisition telemetry

create table if not exists public.search_watches (
  id uuid primary key default gen_random_uuid(),
  marketplace text not null default 'Trade Me',
  name text,
  search_term text not null,
  category text,
  active boolean not null default true,
  interval_hours integer not null default 6 check (interval_hours between 1 and 168),
  max_pages integer not null default 3 check (max_pages between 1 and 20),
  rows_per_page integer not null default 100 check (rows_per_page between 1 and 500),
  next_run_at timestamptz not null default now(),
  last_run_at timestamptz,
  last_status text,
  last_error text,
  discovered_total integer not null default 0,
  known_total integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(marketplace, search_term, category)
);

create index if not exists search_watches_due_idx on public.search_watches(active, next_run_at);

create table if not exists public.search_watch_runs (
  id bigint generated by default as identity primary key,
  watch_id uuid not null references public.search_watches(id) on delete cascade,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','success','partial','failed','skipped')),
  pages_attempted integer not null default 0,
  pages_succeeded integer not null default 0,
  result_count integer not null default 0,
  new_count integer not null default 0,
  known_count integer not null default 0,
  queued_for_observation integer not null default 0,
  http_status integer,
  error_type text,
  error_message text,
  diagnostics jsonb not null default '{}'::jsonb
);

create index if not exists search_watch_runs_watch_idx on public.search_watch_runs(watch_id, started_at desc);

create table if not exists public.listing_acquisition_events (
  id bigint generated by default as identity primary key,
  listing_uuid uuid references public.listings(id) on delete cascade,
  watch_id uuid references public.search_watches(id) on delete set null,
  search_run_id bigint references public.search_watch_runs(id) on delete set null,
  operation text not null,
  source text not null,
  status text not null,
  occurred_at timestamptz not null default now(),
  duration_ms integer,
  http_status integer,
  error_type text,
  error_message text,
  diagnostics jsonb not null default '{}'::jsonb
);

create index if not exists listing_acquisition_events_listing_idx on public.listing_acquisition_events(listing_uuid, occurred_at desc);
create index if not exists listing_acquisition_events_watch_idx on public.listing_acquisition_events(watch_id, occurred_at desc);

alter table public.listings
  add column if not exists source_watch_id uuid references public.search_watches(id) on delete set null,
  add column if not exists discovered_via text,
  add column if not exists last_api_observed_at timestamptz,
  add column if not exists last_api_status text,
  add column if not exists last_api_error_type text,
  add column if not exists last_api_http_status integer,
  add column if not exists last_api_event_at timestamptz,
  add column if not exists last_acquisition_status text,
  add column if not exists last_acquisition_error_type text,
  add column if not exists last_acquisition_event_at timestamptz;

create or replace function public.search_watches_set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists search_watches_set_updated_at on public.search_watches;
create trigger search_watches_set_updated_at before update on public.search_watches
for each row execute function public.search_watches_set_updated_at();

grant select, insert, update, delete on public.search_watches to service_role;
grant select, insert, update, delete on public.search_watch_runs to service_role;
grant select, insert, update, delete on public.listing_acquisition_events to service_role;
grant usage, select on sequence public.search_watch_runs_id_seq to service_role;
grant usage, select on sequence public.listing_acquisition_events_id_seq to service_role;

notify pgrst, 'reload schema';
